name: Deploy na VM

on:
  push:
    branches:
      - main # ou a branch que dispara o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar via SSH e atualizar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }} # opcional, padrão 22
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$NVM_DIR/versions/node/v20.17.0/bin:$PATH"

            echo "Versões:"
            node -v
            npm -v
            which pm2

            cd /root/projeto/frontend
            pm2 stop frontend || true
            git pull origin main
            npm install
            npm run build
            pm2 start frontend
